name: Python Tests and Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint playwright pytest
          playwright install

      - name: Run isort
        run: |
          isort --check --diff task_1/
          isort --check --diff task_2/

      - name: Run flake8
        run: |
          flake8 task_1/ --config=.flake8
          flake8 task_2/ --config=.flake8

      - name: Run pylint
        run: |
          pylint task_1/ --rcfile=.pylintrc
          pylint task_2/ --rcfile=.pylintrc

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest playwright

      - name: Run tests
        run: pytest
